/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jvm_library_test

import kotlin.test.Test
import kotlin.test.assertTrue

class PointlessTest {
    @Test fun assertionsWork() {
        assertTrue(true)
    }
}
